In [1]:
import requests
import pandas as pd
import datetime
import json

In [2]:
response = requests.get('http://127.0.0.1:8000/Envoi/')
response.content

b'Internal Server Error'

In [11]:
from Front.utils import *

response = requests.get(f'http://127.0.0.1:8000/matieres_premieres/')
get_matieres_premieres(response)

('00000QQQQQ', 's0H75wpxf3C9OMTMXw3H', '999999')

In [ ]:
m = requests.get(f'http://127.0.0.1:8000/matieres_premieres/')
n =

,MP_id,MP_nom,MP_codeCW,MP_ref_fournisseur,MP_date_reception,MP_quantite,MP_unite,MP_Analyses
0,1,Potassium,CW_003,9WoHuuWW4Jp1Sv74lYGN,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
1,2,Potassium,CW_003,I2erMP4GUsmJ918tsqrs,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
2,3,Potassium,CW_003,tCbiOkhVjj36ekQk5Zbo,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
3,4,Potassium,CW_003,FzglKkucRX0MkQlZMhIv,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
4,5,Potassium,CW_003,r6DCNmLPuVvnRNvl9dgX,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
...,...,...,...,...,...,...,...,...
205,206,Carbone,CW_001,s0H75wpxf3C9OMTMXw3H,2023-01-01T00:00:00,0.0,Kg,None
206,207,Carbone,CW_001,s0H75wpxf3C9OMTMXw3H,2023-01-01T00:00:00,0.0,Kg,None
207,208,Carbone,CW_001,AIG772GD9,2025-02-04T00:00:00,20.0,Kg,None
208,209,Potassium,CW_002,00000QQQQQ,2025-02-04T00:00:00,10.0,Kg,None
209,210,THF,CW_003,999999,2025-02-04T00:00:00,50.0,L,None

In [6]:
MP

,MP_id,MP_nom,MP_codeCW,MP_ref_fournisseur,MP_date_reception,MP_quantite,MP_unite,MP_Analyses
0,1,Potassium,CW_003,9WoHuuWW4Jp1Sv74lYGN,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
1,2,Potassium,CW_003,I2erMP4GUsmJ918tsqrs,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
2,3,Potassium,CW_003,tCbiOkhVjj36ekQk5Zbo,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
3,4,Potassium,CW_003,FzglKkucRX0MkQlZMhIv,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
4,5,Potassium,CW_003,r6DCNmLPuVvnRNvl9dgX,2023-01-01T00:00:00,0.0,kg,codes_analyses_separated_by_commas
...,...,...,...,...,...,...,...,...
203,204,Potassium,CW_002,9WoHuuWW4Jp1Sv74lYGN,2023-01-01T00:00:00,0.0,L,None
204,205,Carbone,CW_001,s0H75wpxf3C9OMTMXw3H,2023-01-01T00:00:00,0.0,Kg,None
205,206,Carbone,CW_001,s0H75wpxf3C9OMTMXw3H,2023-01-01T00:00:00,0.0,Kg,None
206,207,Carbone,CW_001,s0H75wpxf3C9OMTMXw3H,2023-01-01T00:00:00,0.0,Kg,None
207,208,Carbone,CW_001,AIG772GD9,2025-02-04T00:00:00,20.0,Kg,None

In [7]:
MP.loc[MP.MP_nom=='Carbone',['MP_ref_fournisseur','MP_quantite','MP_unite']]

       MP_ref_fournisseur  MP_quantite MP_unite
201  4qR8YaqQrEo2TJXDnyw7          0.0        L
204  s0H75wpxf3C9OMTMXw3H          0.0       Kg
205  s0H75wpxf3C9OMTMXw3H          0.0       Kg
206  s0H75wpxf3C9OMTMXw3H          0.0       Kg
207             AIG772GD9         20.0       Kg

In [13]:
Envois_all=pd.DataFrame(response.json())
Envois_all.loc[Envois_all.Envoi_produit_batch.isnull(),['Envoi_produit_name','Envoi_produit_Qte']].values

array([], shape=(0, 2), dtype=object)

In [15]:
Envois_all.isnull()

,Envoi_id,Envoi_date_commande,Envoi_client_name,Envoi_produit_name,Envoi_produit_batch,Envoi_produit_Qte,Envoi_produit_emballage,Envoi_date_prevu,Envoi_date_effective,Envoi_code_coli,Envoi_retour_client
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False

In [7]:
response = requests.get('http://127.0.0.1:8000/KC8/name/K2454')
response.json()

{'Batch_KC8_id': 1,
 'Batch_KC8_name': 'K2454',
 'Batch_KC8_date': '2023-07-26T00:00:00',
 'Batch_KC8_Technicien': 'WL',
 'Batch_KC8_K_batch': 'icjb7a3BpUqaAjdfTFwO',
 'Batch_KC8_C_batch': 'CGjZ1rAL5Gr8g47JpraI',
 'Batch_KC8_masse': 200,
 'Batch_KC8_Temperature': 60.0,
 'Batch_KC8_Agitation': 250,
 'Batch_KC8_heure_debut': '2023-07-26T12:00:00',
 'Batch_KC8_heure_fin': '2023-07-26T14:00:00',
 'Batch_KC8_room_HR': 28.0,
 'Batch_KC8_room_T': 0.3,
 'Batch_KC8_Analyses': 'codes_analyses_separated_by_commas'}

In [9]:
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json'}

data = {"Batch_KC8_id": 199, "Batch_KC8_name": "K2403", "Batch_KC8_date": "2025-01-03T00:00:00", "Batch_KC8_Technicien": "LC", "Batch_KC8_K_batch": "XM1DlrekybkXzl4ZKXDC", "Batch_KC8_C_batch": "amqaNvqew67D345ZESZ1", "Batch_KC8_masse": 150, "Batch_KC8_Temperature": 60.0, "Batch_KC8_Agitation": 250, "Batch_KC8_heure_debut": "2025-01-03T12:00:00", "Batch_KC8_heure_fin": "2025-01-03T15:00:00", "Batch_KC8_room_HR": 20.0, "Batch_KC8_room_T": 0.2, "Batch_KC8_Analyses": "codes_analyses_separated_by_commas"}

response = requests.post(f'http://127.0.0.1:8000/KC8/update/199', headers=headers, data=json.dumps(data))

In [11]:
response.content

b'Internal Server Error'

In [ ]:
analyses_UV = pd.DataFrame(response.json()).sort_values('Batch_OGD_id', ascending=False)

In [36]:
UV_OGD[['Analyse_UV_name','conc']]

,Analyses_UV_id,Analyse_UV_name,Analyse_UV_subname,Analyse_UV_details,Analyses_UV_data,conc
0,1,OGD2415D,UV,"{'dillution': '1:10', 'centrifuge': False}","{'200': 0.07011012641841068, '210': 0.08197060...",0.007011

    Batch_OGD_name       Batch_OGD_date  Batch_OGD_KC8_masse
0         OGD2415D  2024-01-26T00:00:00                 20.0
1         OGD2307D  2023-08-05T00:00:00                 20.0
2         OGD2353D  2023-09-14T00:00:00                 20.0
3         OGD2323B  2023-10-11T00:00:00                 20.0
4         OGD2334C  2023-06-03T00:00:00                 20.0
..             ...                  ...                  ...
161       OGD2311A  2024-04-10T00:00:00                 20.0
162       OGD2437D  2023-06-14T00:00:00                 20.0
163       OGD2446A  2024-05-08T00:00:00                 20.0
164       OGD2504A  2025-01-24T00:00:00                 50.0
165        OGD2505  2025-01-27T00:00:00                250.0

[166 rows x 3 columns]

In [40]:
df

,Batch_OGD_name,Batch_OGD_date,Batch_OGD_KC8_masse,Analyse_UV_name,conc
0,OGD2415D,2024-01-26T00:00:00,20.0,OGD2415D,0.007011

## test graphs plotly in front

In [45]:
import plotly
import plotly.express as px


# get data from bdd
    # analyses UV
url = 'http://127.0.0.1:8000/'
headers = {
'accept': 'application/json',
'Content-Type': 'application/json'}
response = requests.get(url+f'analyses_UV',headers=headers)
UV_OGD = pd.DataFrame(response.json())
UV_OGD['conc'] = UV_OGD[['Analyse_UV_name','Analyse_UV_details','Analyses_UV_data']].apply(lambda x: x[2]['200'] / float(x[1]['dillution'].split(':')[1]), axis=1)
    # info batch date
response = requests.get(url+f'OGD',headers=headers)
batch_OGD = pd.DataFrame(response.json())

# create new df
df=pd.merge(batch_OGD[['Batch_OGD_name','Batch_OGD_date','Batch_OGD_KC8_masse']],
         UV_OGD[['Analyse_UV_name','conc']],
         left_on='Batch_OGD_name',
         right_on='Analyse_UV_name',
         how='inner')
    # format date
df['Batch_OGD_date'] = pd.to_datetime(df['Batch_OGD_date'])
df['week'] = df.Batch_OGD_date.apply(lambda x : x.week) #df.Batch_name.apply(lambda x : pd.to_datetime(int(x[2:4]),unit='W').week)  # df['date'].dt.week # 
df['month'] = df.Batch_OGD_date.apply(lambda x : x.month) #Batch_name.apply(lambda x : pd.to_datetime(int(x[2:4]),unit='W').month) # df['date'].dt.month # 
df['year'] = df.Batch_OGD_date.apply(lambda x : x.year)
df.Batch_OGD_KC8_masse = df.Batch_OGD_KC8_masse.apply(lambda x : int(round(x)))
    # Pivot Table
table = pd.pivot_table(df, 
                index=[ 'month', 'week'], 
                values=['Batch_OGD_name', 'conc'], 
                aggfunc={'Batch_OGD_name': 'count', 'conc': ['sum', 'mean']})
    # create graph
fig = px.box(df, x='Batch_OGD_date', y="conc", points="all")
graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

/var/folders/dv/gzhyqctn53s9bh23g7tbvl940000gn/T/ipykernel_51658/1132335657.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  UV_OGD['conc'] = UV_OGD[['Analyse_UV_name','Analyse_UV_details','Analyses_UV_data']].apply(lambda x: x[2]['200'] / float(x[1]['dillution'].split(':')[1]), axis=1)